apiVersion: v1
kind: Namespace
metadata:
  name: kang-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kang-agent
  namespace: kang-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kang-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kang-agent
    spec:
      hostPID: true
      containers:
        - name: kang-agent
          image: ghcr.io/project-kang/kang-agent:dev
          imagePullPolicy: IfNotPresent
          args:
            - "--listen=:8081"
            - "--host-id=$(NODE_NAME)"
            - "--vm-driver=virsh"
            - "--virsh-path=virsh"
            - "--libvirt-network=default"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8081
          securityContext:
            privileged: true
          volumeMounts:
            - name: libvirt-run
              mountPath: /var/run/libvirt
            - name: libvirt-images
              mountPath: /var/lib/libvirt/images
            - name: dev-kvm
              mountPath: /dev/kvm
      volumes:
        - name: libvirt-run
          hostPath:
            path: /var/run/libvirt
            type: DirectoryOrCreate
        - name: libvirt-images
          hostPath:
            path: /var/lib/libvirt/images
            type: DirectoryOrCreate
        - name: dev-kvm
          hostPath:
            path: /dev/kvm
            type: CharDevice
